import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import ArticleCard from './components/ArticleCard';
import { useState, useEffect } from 'react';

import { gql } from '@apollo/client';

import { getApolloClient } from './api/hello';

const inter = Inter({ subsets: ['latin'] });



const SliderData = [
  {
    image: "https://scarlettdata.online/wp-content/uploads/2022/10/5.jpg",
  },
  {
    image: "https://scarlettdata.online/wp-content/uploads/2022/10/3-scaled.jpg",
  },
  {
    image: "https://scarlettdata.online/wp-content/uploads/2022/10/1-1-scaled.jpg",
  },
];

export default function Home({ page, posts }) {
  const [current, setCurrent] = useState(0)

  const [animate, setAnimate] = useState(false);
  const length = SliderData.length

  

  const nextSlide = () => {
    setCurrent(current === length - 1 ? 0 : current + 1)
    setAnimate(!animate);
  }

  

  const handleClick = () => setAnimate(!animate);

  useEffect(() => {
    console.log(current);
  }, [current]);
  return (
    <>
      <Head>
        <title>Scarlett Casciello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div class="home_section">
          <div className="gallery_section">
          <img class="slide_img" src="https://scarlettdata.online/wp-content/uploads/2022/10/5.jpg"></img>
          </div>
            {/* {SliderData.map((slide, index) => {
              return (
                <div
                  className={
                    index === current
                      ? 'gallery_section active'
                      : 'gallery_section'
                  }
                  key={index}
                >
                  {index === current && (
                    <img
                      onClick={nextSlide}
                      class="active_slide_img"
                      src={slide.image}
                    />
                  )}
                </div>
              );
            })} */}
          {/* </div> */}

          <p class="desktop_menu">
            <a href="">Home</a>,
            <a href="">Works</a>,
            <a href="">About</a>,
            <a href="">Contact</a>
          </p>
        </div>
        {/* <ArticleCard posts={posts} pages={page} /> */}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const apolloClient = getApolloClient();

  const data = await apolloClient.query({
    query: gql`
      {
        generalSettings {
          title
          description
        }

        posts(first: 9) {
          edges {
            node {
              id
              excerpt
              title
              slug
              featuredImage {
                node {
                  mediaItemUrl
                }
              }
            }
          }
        }
      }
    `,
  });

  const posts = data?.data.posts.edges
    .map(({ node }) => node)
    .map((post) => {
      return {
        ...post,
        path: `/posts/${post.slug}`,
      };
    });

  const page = {
    ...data?.data.generalSettings,
  };

  return {
    props: {
      page,
      posts,
    },
  };
}
